#%RAML 1.0 Trait

client_id_required:
    headers:
      client_id:
        type: string
        required: true
        description: provied by API manager
      client_secret:
        type: string
        required: true
        description: provided by API manager